---
#  Copyright (c) 2019 Red Hat, Inc.
#
#  This file is part of ARA Records Ansible.
#
#  ARA Records Ansible is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ARA Records Ansible is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ARA Records Ansible. If not, see <http://www.gnu.org/licenses/>.

- name: Validate if the distribution is supported
  fail:
    msg: |
      {{ ansible_facts['distribution'] }} does not support installation from distribution packages yet.
  when: ara_distribution_packages | length == 0

- name: Install ara from distribution packages
  become: yes
  package:
    name: "{{ ara_distribution_packages }}"
    state: present

# TODO: consider putting the name of the package into a variable if distributions
# other than fedora become supported.
- name: Install python-passlib for managing authentication credentials
  become: yes
  package:
    name: python3-passlib
    state: present
  when: ara_api_external_auth

# This lets us use "path_with_virtualenv" without conditions everywhere
- name: Don't prefix the virtualenv bin directory to PATH
  set_fact:
    path_with_virtualenv: "{{ ansible_facts['env']['PATH'] }}"
