---
- name: Install required packages from Pypi
  pip:
    name: ara[server]
    state: present
    virtualenv: "{{ ara_api_venv | bool | ternary(ara_api_venv_path, omit) }}"
    virtualenv_command: /usr/bin/python3 -m venv

- name: Prefix the virtualenv bin directory to PATH
  set_fact:
    path_with_virtualenv: "{{ ara_api_venv_path }}/bin:{{ ansible_facts['env']['PATH'] }}"
  when: ara_api_venv | bool
