---
#  Copyright (c) 2019 Red Hat, Inc.
#
#  This file is part of ARA Records Ansible.
#
#  ARA Records Ansible is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ARA Records Ansible is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ARA Records Ansible. If not, see <http://www.gnu.org/licenses/>.

- name: Retrieve list of missing required packages for mysql
  set_fact:
    _mysql_missing_packages: "{{ ara_api_mysql_packages | difference(ansible_facts.packages.keys()) }}"

# Only attempt to elevate privileges if there are any missing packages
- when: _mysql_missing_packages | length > 0
  block:
    - name: Install required packages
      become: true
      package:
        name: "{{ ara_api_mysql_packages }}"
        state: present
  rescue:
    - name: Fail due to missing packages
      fail:
        msg: |
          Failed to elevate privileges and install missing required packages.
          Install the following packages before running this role again:
          {{ _mysql_missing_packages | join(' ') }}

# Django requires mysqclient when using mysql
# https://docs.djangoproject.com/en/2.2/ref/databases/#mysql-db-api-drivers
- name: Ensure mysqlclient is installed
  pip:
    name: mysqlclient
    state: present
    virtualenv: "{{ ara_api_venv | bool | ternary(ara_api_venv_path, omit) }}"
    virtualenv_command: /usr/bin/python3 -m venv

- name: Run SQL migrations
  environment:
    ARA_SETTINGS: "{{ ara_api_settings }}"
    PATH: "{{ path_with_virtualenv }}"
  command: ara-manage migrate
  run_once: true
  register: _ara_sql_migrations
  retries: 3
  delay: 5
  until: _ara_sql_migrations is succeeded
  changed_when: "'No migrations to apply' not in _ara_sql_migrations.stdout"
