---
#  Copyright (c) 2019 Red Hat, Inc.
#
#  This file is part of ARA Records Ansible.
#
#  ARA Records Ansible is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ARA Records Ansible is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ARA Records Ansible. If not, see <http://www.gnu.org/licenses/>.

- name: Install gunicorn
  pip:
    name: gunicorn
    state: present
    virtualenv: "{{ ara_api_venv | bool | ternary(ara_api_venv_path, omit) }}"
    virtualenv_command: "{{ ara_api_python_command }} -m venv"

- name: Get path to gunicorn
  command: which gunicorn
  changed_when: false
  register: _gunicorn_cmd
  environment:
    PATH: "{{ path_with_virtualenv }}"

- name: Set path to gunicorn
  set_fact:
    _gunicorn_path: "{{ _gunicorn_cmd.stdout }}"

- when: ansible_facts['os_family'] == "RedHat"
  block:
    - name: Transfer gunicorn selinux type enforcement file
      copy:
        src: ara-gunicorn.te
        dest: "{{ ara_api_root_dir }}/ara-gunicorn.te"
        mode: 0444
      register: ara_selinux_module_file

    - name: Compile ara-gunicorn selinux module
      command: "checkmodule -M -m -o {{ ara_api_root_dir }}/ara-gunicorn.mod {{ ara_api_root_dir }}/ara-gunicorn.te"
      when: ara_selinux_module_file['changed']

    - name: Compile ara-gunicorn selinux policy package
      command: "semodule_package -o {{ ara_api_root_dir }}/ara-gunicorn.pp -m {{ ara_api_root_dir }}/ara-gunicorn.mod"
      when: ara_selinux_module_file['changed']

- become: true
  block:
    - name: Gather loaded SELinux modules
      command: semodule -l
      register: ara_selinux_modules_loaded
      when: ansible_facts['os_family'] == "RedHat"
      changed_when: false

    - name: Install selinux policy package
      command: "semodule -i {{ ara_api_root_dir }}/ara-gunicorn.pp"
      when:
        - ansible_facts['os_family'] == "RedHat"
        - ('ara-gunicorn' not in ara_selinux_modules_loaded['stdout_lines'] or ara_selinux_module_file['changed'])

    - name: Set up systemd unit file for gunicorn to run the ARA API
      template:
        src: ara-api.service.j2
        dest: /etc/systemd/system/ara-api.service
        owner: root
        group: root
        mode: 0644
      notify:
        - restart ara-api

    - name: Enable and start ara-api with gunicorn
      service:
        name: ara-api
        state: started
        enabled: true
        daemon_reload: true
      register: ara_api_service_enabled
