---
#  Copyright (c) 2019 Red Hat, Inc.
#
#  This file is part of ARA Records Ansible.
#
#  ARA Records Ansible is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ARA Records Ansible is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ARA Records Ansible. If not, see <http://www.gnu.org/licenses/>.

# ARA has not been packaged for CentOS or RHEL yet
ara_distribution_packages: []

# EL8 doesn't install a python3 interpreter by default.
# System packages rely on /usr/libexec/platform-python and Ansible will use it
# but we want to use the non-system one. Install it if it's missing.
ara_api_required_packages:
  - git
  - python36
  - policycoreutils-python-utils
  # cronie provides crontab
  - cronie

ara_api_postgresql_packages:
  - postgresql
  - postgresql-devel
  - python36-devel
  - gcc

ara_api_mysql_packages:
  - mariadb
  - mariadb-connector-c-devel
  - redhat-rpm-config
  - python36-devel
  - gcc
