---
#  Copyright (c) 2019 Red Hat, Inc.
#
#  This file is part of ARA Records Ansible.
#
#  ARA Records Ansible is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ARA Records Ansible is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ARA Records Ansible. If not, see <http://www.gnu.org/licenses/>.

- name: Include OS family/distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}.yaml"
    - "{{ ansible_facts['os_family'] }}.yaml"

- become: yes
  block:
    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Set selinux boolean to allow nginx to reverse proxy
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
      when: ansible_facts['os_family'] == "RedHat"

    - when: ara_api_fqdn is defined
      block:
        - name: Set up the ARA API nginx vhost
          template:
            src: "{{ ara_api_frontend_vhost | default('ara-api.conf.j2', True) }}"
            dest: "{{ ara_nginx_config_path }}/ara-api.conf"
          notify:
            - restart nginx

        - name: Enable the API nginx configuration on Debian-like systems
          file:
            src: "{{ ara_nginx_config_path }}/ara-api.conf"
            dest: /etc/nginx/sites-enabled/ara-api.conf
            state: link
          when: ansible_facts['os_family'] == 'Debian'
          notify:
            - restart nginx

    - when: ara_web_fqdn is defined
      block:
        - name: Set up the ARA API nginx vhost
          template:
            src: "{{ ara_web_frontend_vhost | default('ara-web.conf.j2', True) }}"
            dest: "{{ ara_nginx_config_path }}/ara-web.conf"
          notify:
            - restart nginx

        - name: Enable the web nginx configuration on Debian-like systems
          file:
            src: "{{ ara_nginx_config_path }}/ara-web.conf"
            dest: /etc/nginx/sites-enabled/ara-web.conf
            state: link
          when: ansible_facts['os_family'] == 'Debian'
          notify:
            - restart nginx

    - name: Enable and start nginx
      service:
        name: nginx
        state: started
        enabled: yes
      register: ara_nginx_enabled
