- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ara-role-api-distributed-sqlite
        - ara-role-api-mysql
        - ara-role-api-postgresql
        - ara-role-api-gunicorn-nginx
        - ara-role-api-fedora-packages:
            voting: false
    gate:
      jobs:
        - ara-role-api-distributed-sqlite
        - ara-role-api-mysql
        - ara-role-api-postgresql
        - ara-role-api-gunicorn-nginx
